language: generic
sudo: required
dist: trusty

matrix:
  include:
    - os: osx
      osx_image: xcode9.4 
      env: MONGODB_VERSION=3.6.5 SWIFT_VERSION=4.0
    - os: osx
      osx_image: xcode9.4
      env: MONGODB_VERSION=3.6.5 SWIFT_VERSION=4.1
    - os: osx
      osx_image: xcode10.1
      env: MONGODB_VERSION=3.6.5 SWIFT_VERSION=4.1
    - os: osx
      osx_image: xcode10.1
      env: MONGODB_VERSION=3.6.5 SWIFT_VERSION=4.2 
    - name: Lint
      os: osx
      env: LINT=TRUE
    - os: linux
      env: MONGODB_VERSION=3.6.5 SWIFT_VERSION=4.0
    - os: linux
      env: MONGODB_VERSION=3.6.5 SWIFT_VERSION=4.1
    - os: linux
      env: MONGODB_VERSION=3.6.5 SWIFT_VERSION=4.2

install:
  - ./travis_install.sh

before_script:
  - if [[ "$LINT" != "TRUE" ]]; mkdir ${PWD}/mongodb-${MONGODB_VERSION}/data; ${PWD}/mongodb-${MONGODB_VERSION}/bin/mongod --dbpath ${PWD}/mongodb-${MONGODB_VERSION}/data --logpath ${PWD}/mongodb-${MONGODB_VERSION}/mongodb.log --enableMajorityReadConcern --fork; fi

script:
  - if [[ "$LINT" == "TRUE" ]]; then brew upgrade swiftlint; swiftlint --strict; fi 
  - if [[ "$LINT" != "TRUE" ]]; then swift build -v; swift test -v; fi
